version = 0.1

[default.deploy.parameters]
stack_name = "getContactById"
resolve_s3 = true
s3_prefix = "getContactById"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
